### ISSUE TITLE
size_average True or False?

### ISSUE THREAD

**Issue by TuoniTuoni** [ZhongyuanW/SSD_mobilenetv2-with-Focal-loss#2]
And when training, size_average should be set False or True can have a better result?

**Comment by ZhongyuanW** [comment]
@TuoniTuoni It doesn't matter. In fact, i set size_average Flase but means it at there. 
![image](https://user-images.githubusercontent.com/27918429/67281268-9d0a9680-f501-11e9-89eb-c73c1918b5c6.png)
