### ISSUE TITLE
run eval.py error

### ISSUE THREAD

**Issue by immarioo** [ZhongyuanW/SSD_mobilenetv2-with-Focal-loss#3]
hi, thanks for your sharing.
i refer your repo and change the backbone vgg with mobilenetv2, and i trained 40w iters, but when i run eval.py i get error like this: RuntimeError: shape '[1, 8732, 2]' is invalid for input of size 4556. i konw the 8732 is the default box of vgg, but i really changed the backbone with mobilenetv2, and i test my model in your repo, it is the same error, please help.
![ssd](https://user-images.githubusercontent.com/12837585/69524389-e63a8400-0fa0-11ea-89f8-e2e25d2459e7.png)

**Comment by ZhongyuanW** [comment]
maybe there is something wrong in your detect.py. you should check it.
![image](https://user-images.githubusercontent.com/27918429/69849182-f57a4400-12b6-11ea-9f71-4f8864eaec21.png)

**Comment by immarioo** [comment]
thanks, i made a mistake in my config.py.
