### ISSUE TITLE
mobilenetv2.py

### ISSUE THREAD

**Issue by immarioo** [ZhongyuanW/SSD_mobilenetv2-with-Focal-loss#4]
你好，我在阅读你的mobilenetv2.py代码中，好像由于num_channels=[32,16,24,32,64,96,160,320]相邻通道数不同，不满足条件并没有使用倒残差，不知道是不是我理解的不对？求解答

**Comment by ZhongyuanW** [comment]
你好，这个的num_channels是指每个bottleneck最后一层输出的通道数。
但是在每个bottleneck里面会重复有几个linearbottleneck，linearbottleneck里面会用到残差。

**Comment by immarioo** [comment]
非常感谢，已经理解了。
